-- NorthWind Payments — Snowflake PII governance.
-- Mirrors databricks/notebooks/04_setup_security.sql + 05_apply_pii_masks.sql.
-- Members of NPL_PII_READER (or ACCOUNTADMIN) see plaintext; everyone else sees masked.

USE WAREHOUSE NORTHWIND_WH;
USE DATABASE NORTHWIND_PAYMENTS;
USE SCHEMA SECURITY;

-- 1. Credit-card numbers — show last 4 only
CREATE OR REPLACE MASKING POLICY mask_cc_num AS (val STRING) RETURNS STRING ->
    CASE
        WHEN current_role() IN ('NPL_PII_READER', 'ACCOUNTADMIN') THEN val
        WHEN val IS NULL THEN NULL
        ELSE '************' || RIGHT(val, 4)
    END;

-- 2. Names — REDACTED
CREATE OR REPLACE MASKING POLICY mask_name AS (val STRING) RETURNS STRING ->
    CASE
        WHEN current_role() IN ('NPL_PII_READER', 'ACCOUNTADMIN') THEN val
        WHEN val IS NULL THEN NULL
        ELSE 'REDACTED'
    END;

-- 3. Street address — REDACTED
CREATE OR REPLACE MASKING POLICY mask_street AS (val STRING) RETURNS STRING ->
    CASE
        WHEN current_role() IN ('NPL_PII_READER', 'ACCOUNTADMIN') THEN val
        WHEN val IS NULL THEN NULL
        ELSE 'REDACTED'
    END;

-- 4. Date of birth — NULL out
CREATE OR REPLACE MASKING POLICY mask_dob AS (val STRING) RETURNS STRING ->
    CASE
        WHEN current_role() IN ('NPL_PII_READER', 'ACCOUNTADMIN') THEN val
        ELSE NULL
    END;

-- 5. Apply policies to silver.customers_snapshot
USE SCHEMA SILVER;

ALTER TABLE NORTHWIND_PAYMENTS.SILVER.CUSTOMERS_SNAPSHOT
    MODIFY COLUMN cc_num SET MASKING POLICY NORTHWIND_PAYMENTS.SECURITY.mask_cc_num FORCE;
ALTER TABLE NORTHWIND_PAYMENTS.SILVER.CUSTOMERS_SNAPSHOT
    MODIFY COLUMN first  SET MASKING POLICY NORTHWIND_PAYMENTS.SECURITY.mask_name FORCE;
ALTER TABLE NORTHWIND_PAYMENTS.SILVER.CUSTOMERS_SNAPSHOT
    MODIFY COLUMN last   SET MASKING POLICY NORTHWIND_PAYMENTS.SECURITY.mask_name FORCE;
ALTER TABLE NORTHWIND_PAYMENTS.SILVER.CUSTOMERS_SNAPSHOT
    MODIFY COLUMN street SET MASKING POLICY NORTHWIND_PAYMENTS.SECURITY.mask_street FORCE;
ALTER TABLE NORTHWIND_PAYMENTS.SILVER.CUSTOMERS_SNAPSHOT
    MODIFY COLUMN dob    SET MASKING POLICY NORTHWIND_PAYMENTS.SECURITY.mask_dob FORCE;

-- 6. Mask cc_num on silver.transactions too
ALTER TABLE NORTHWIND_PAYMENTS.SILVER.TRANSACTIONS
    MODIFY COLUMN cc_num SET MASKING POLICY NORTHWIND_PAYMENTS.SECURITY.mask_cc_num FORCE;

-- 7. Verify
SHOW MASKING POLICIES IN SCHEMA NORTHWIND_PAYMENTS.SECURITY;
